artifact_location: file:///Users/Sanjay/Desktop/GUVI/project 4/patroliq2/mlruns/423282679409158820
creation_time: 1777978355856
experiment_id: '423282679409158820'
last_update_time: 1777978355856
lifecycle_stage: active
name: Geographic_Clustering
trace_location: null
workspace: default
