artifact_location: file:///Users/Sanjay/Desktop/GUVI/project 4/patroliq2/mlruns/159945545267522088
creation_time: 1777980874670
experiment_id: '159945545267522088'
last_update_time: 1777980874670
lifecycle_stage: active
name: Dimensionality_Reduction
trace_location: null
workspace: default
